services:
  database:
    container_name: fitematch-database
    image: mongo:8.0
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./.mongodb:/data/db
    ports:
      - ${DATABASE_BIND_PORT}:${DATABASE_PORT}
    command: ['mongod', '--port', '${DATABASE_PORT}']
    networks:
      - fitematch

  api:
    container_name: fitematch-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: fitematch-api:development
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${APPLICATION_BIND_PORT}:${APPLICATION_PORT}
    networks:
      - fitematch

networks:
  fitematch:
    driver: bridge
