export const SIGN_UP_USE_CASE = Symbol('SIGN_UP_USE_CASE');
export const SIGN_UP_REPOSITORY = Symbol('SIGN_UP_REPOSITORY');

export const SIGN_IN_USE_CASE = Symbol('SIGN_IN_USE_CASE');
export const SIGN_IN_REPOSITORY = Symbol('SIGN_IN_REPOSITORY');

export const SIGN_OUT_USE_CASE = Symbol('SIGN_OUT_USE_CASE');

export const GET_ME_USE_CASE = Symbol('GET_ME_USE_CASE');
export const GET_ME_REPOSITORY = Symbol('GET_ME_REPOSITORY');

export const UPDATE_ME_USE_CASE = Symbol('UPDATE_ME_USE_CASE');
export const UPDATE_ME_REPOSITORY = Symbol('UPDATE_ME_REPOSITORY');

export const CREATE_ACTIVATION_CODE_USE_CASE = Symbol(
  'CREATE_ACTIVATION_CODE_USE_CASE',
);
export const CREATE_ACTIVATION_CODE_REPOSITORY = Symbol(
  'CREATE_ACTIVATION_CODE_REPOSITORY',
);

export const ACTIVATE_ACCOUNT_USE_CASE = Symbol('ACTIVATE_ACCOUNT_USE_CASE');
export const ACTIVATE_ACCOUNT_REPOSITORY = Symbol(
  'ACTIVATE_ACCOUNT_REPOSITORY',
);

export const REFRESH_TOKEN_USE_CASE = Symbol('REFRESH_TOKEN_USE_CASE');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');

export const ACTIVATION_CODE_REPOSITORY = Symbol('ACTIVATION_CODE_REPOSITORY');

export const HASH_SERVICE = Symbol('HASH_SERVICE');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
