export const LIST_COMPANY_USE_CASE = Symbol('LIST_COMPANY_USE_CASE');
export const LIST_COMPANY_REPOSITORY = Symbol('LIST_COMPANY_REPOSITORY');
export const CREATE_COMPANY_USE_CASE = Symbol('CREATE_COMPANY_USE_CASE');
export const CREATE_COMPANY_REPOSITORY = Symbol('CREATE_COMPANY_REPOSITORY');
export const READ_COMPANY_USE_CASE = Symbol('READ_COMPANY_USE_CASE');
export const READ_COMPANY_REPOSITORY = Symbol('READ_COMPANY_REPOSITORY');
export const UPDATE_COMPANY_USE_CASE = Symbol('UPDATE_COMPANY_USE_CASE');
export const UPDATE_COMPANY_REPOSITORY = Symbol('UPDATE_COMPANY_REPOSITORY');
export const DELETE_COMPANY_USE_CASE = Symbol('DELETE_COMPANY_USE_CASE');
export const DELETE_COMPANY_REPOSITORY = Symbol('DELETE_COMPANY_REPOSITORY');
export const LIST_PUBLIC_COMPANIES_USE_CASE = Symbol(
  'LIST_PUBLIC_COMPANIES_USE_CASE',
);
export const LIST_PUBLIC_COMPANIES_REPOSITORY = Symbol(
  'LIST_PUBLIC_COMPANIES_REPOSITORY',
);
