export const LIST_COMPANY_USE_CASE = Symbol('LIST_COMPANY_USE_CASE');
export const LIST_COMPANY_REPOSITORY = Symbol('LIST_COMPANY_REPOSITORY');
export const CREATE_COMPANY_USE_CASE = Symbol('CREATE_COMPANY_USE_CASE');
export const CREATE_COMPANY_REPOSITORY = Symbol('CREATE_COMPANY_REPOSITORY');
