export const MIGRATION_RUNNER = Symbol('MIGRATION_RUNNER');
export const MIGRATION_ROLLBACK_RUNNER = Symbol('MIGRATION_ROLLBACK_RUNNER');
export const SEED_RUNNER = Symbol('SEED_RUNNER');
export const SEED_ROLLBACK_RUNNER = Symbol('SEED_ROLLBACK_RUNNER');
export const DATABASE_LOCK_MANAGER = Symbol('DATABASE_LOCK_MANAGER');
