export const CREATE_APPLY_USE_CASE = Symbol('CREATE_APPLY_USE_CASE');
export const CREATE_APPLY_REPOSITORY = Symbol('CREATE_APPLY_REPOSITORY');
export const LIST_APPLY_USE_CASE = Symbol('LIST_APPLY_USE_CASE');
export const LIST_APPLY_REPOSITORY = Symbol('LIST_APPLY_REPOSITORY');
export const READ_APPLY_USE_CASE = Symbol('READ_APPLY_USE_CASE');
export const READ_APPLY_REPOSITORY = Symbol('READ_APPLY_REPOSITORY');
