export enum PermissionEnum {
  CREATE_USERS = 'create_users',
  READ_USERS = 'read_users',
  UPDATE_USERS = 'update_users',
  DELETE_USERS = 'delete_users',
  READ_OWN_USER = 'read_own_user',
  UPDATE_OWN_USER = 'update_own_user',

  CREATE_COMPANIES = 'create_companies',
  READ_COMPANIES = 'read_companies',
  UPDATE_COMPANIES = 'update_companies',
  DELETE_COMPANIES = 'delete_companies',
  READ_OWN_COMPANY = 'read_own_company',
  UPDATE_OWN_COMPANY = 'update_own_company',

  CREATE_JOBS = 'create_jobs',
  READ_JOBS = 'read_jobs',
  UPDATE_JOBS = 'update_jobs',
  DELETE_JOBS = 'delete_jobs',
  READ_OWN_JOBS = 'read_own_jobs',
  UPDATE_OWN_JOBS = 'update_own_jobs',
  DELETE_OWN_JOBS = 'delete_own_jobs',
  APPROVE_JOBS = 'approve_jobs',
  REJECT_JOBS = 'reject_jobs',

  CREATE_APPLIES = 'create_applies',
  READ_APPLIES = 'read_applies',
  UPDATE_APPLIES = 'update_applies',
  DELETE_APPLIES = 'delete_applies',
  READ_OWN_APPLIES = 'read_own_applies',
  DELETE_OWN_APPLIES = 'delete_own_applies',
  UPDATE_OWN_APPLIES = 'update_own_applies',
  READ_JOB_APPLIES = 'read_job_applies',
  REVIEW_APPLIES = 'review_applies',
  APPROVE_APPLIES = 'approve_applies',
  REJECT_APPLIES = 'reject_applies',
}
