export enum SoftSkillsEnum {
  COMMUNICATION = 'communication',
  EMPATHY = 'empathy',
  LEADERSHIP = 'leadership',
  MOTIVATION = 'motivation',
  PROACTIVITY = 'proactivity',
  TEAMWORK = 'teamwork',
  ADAPTABILITY = 'adaptability',
  DISCIPLINE = 'discipline',
  ORGANIZATION = 'organization',
  TIME_MANAGEMENT = 'time_management',
  CUSTOMER_SERVICE = 'customer_service',
  ACTIVE_LISTENING = 'active_listening',
  CONFLICT_RESOLUTION = 'conflict_resolution',
  PROBLEM_SOLVING = 'problem_solving',
  RESILIENCE = 'resilience',
  PROFESSIONAL_ETHICS = 'professional_ethics',
  RESPONSIBILITY = 'responsibility',
  PATIENCE = 'patience',
  ATTENTION_TO_DETAIL = 'attention_to_detail',
  POSITIVE_ATTITUDE = 'positive_attitude',
}
