export const LIST_EMAIL_TEMPLATE_USE_CASE = Symbol(
  'LIST_EMAIL_TEMPLATE_USE_CASE',
);
export const LIST_EMAIL_TEMPLATE_REPOSITORY = Symbol(
  'LIST_EMAIL_TEMPLATE_REPOSITORY',
);

export const READ_EMAIL_TEMPLATE_USE_CASE = Symbol(
  'READ_EMAIL_TEMPLATE_USE_CASE',
);
export const READ_EMAIL_TEMPLATE_REPOSITORY = Symbol(
  'READ_EMAIL_TEMPLATE_REPOSITORY',
);

export const UPDATE_EMAIL_TEMPLATE_USE_CASE = Symbol(
  'UPDATE_EMAIL_TEMPLATE_USE_CASE',
);
export const UPDATE_EMAIL_TEMPLATE_REPOSITORY = Symbol(
  'UPDATE_EMAIL_TEMPLATE_REPOSITORY',
);

export const RESET_EMAIL_TEMPLATE_USE_CASE = Symbol(
  'RESET_EMAIL_TEMPLATE_USE_CASE',
);
export const RESET_EMAIL_TEMPLATE_REPOSITORY = Symbol(
  'RESET_EMAIL_TEMPLATE_REPOSITORY',
);

export const TEST_EMAIL_TEMPLATE_USE_CASE = Symbol(
  'TEST_EMAIL_TEMPLATE_USE_CASE',
);
export const TEST_EMAIL_TEMPLATE_REPOSITORY = Symbol(
  'TEST_EMAIL_TEMPLATE_REPOSITORY',
);
