export const LIST_USER_USE_CASE = Symbol('LIST_USER_USE_CASE');
export const LIST_USER_REPOSITORY = Symbol('LIST_USER_REPOSITORY');
export const CREATE_USER_USE_CASE = Symbol('CREATE_USER_USE_CASE');
export const CREATE_USER_REPOSITORY = Symbol('CREATE_USER_REPOSITORY');
export const READ_USER_USE_CASE = Symbol('READ_USER_USE_CASE');
export const READ_USER_REPOSITORY = Symbol('READ_USER_REPOSITORY');
export const UPDATE_USER_USE_CASE = Symbol('UPDATE_USER_USE_CASE');
export const UPDATE_USER_REPOSITORY = Symbol('UPDATE_USER_REPOSITORY');
