export const LIST_JOB_USE_CASE = Symbol('LIST_JOB_USE_CASE');
export const LIST_JOB_REPOSITORY = Symbol('LIST_JOB_REPOSITORY');

export const CREATE_JOB_USE_CASE = Symbol('CREATE_JOB_USE_CASE');
export const CREATE_JOB_REPOSITORY = Symbol('CREATE_JOB_REPOSITORY');

export const READ_JOB_USE_CASE = Symbol('READ_JOB_USE_CASE');
export const READ_JOB_REPOSITORY = Symbol('READ_JOB_REPOSITORY');

export const UPDATE_JOB_USE_CASE = Symbol('UPDATE_JOB_USE_CASE');
export const UPDATE_JOB_REPOSITORY = Symbol('UPDATE_JOB_REPOSITORY');

export const DELETE_JOB_USE_CASE = Symbol('DELETE_JOB_USE_CASE');
export const DELETE_JOB_REPOSITORY = Symbol('DELETE_JOB_REPOSITORY');

export const LIST_MY_JOBS_USE_CASE = Symbol('LIST_MY_JOBS_USE_CASE');
export const LIST_MY_JOBS_REPOSITORY = Symbol('LIST_MY_JOBS_REPOSITORY');

export const CREATE_MY_JOB_USE_CASE = Symbol('CREATE_MY_JOB_USE_CASE');
export const CREATE_MY_JOB_REPOSITORY = Symbol('CREATE_MY_JOB_REPOSITORY');

export const UPDATE_MY_JOB_USE_CASE = Symbol('UPDATE_MY_JOB_USE_CASE');
export const UPDATE_MY_JOB_REPOSITORY = Symbol('UPDATE_MY_JOB_REPOSITORY');

export const DELETE_MY_JOB_USE_CASE = Symbol('DELETE_MY_JOB_USE_CASE');
export const DELETE_MY_JOB_REPOSITORY = Symbol('DELETE_MY_JOB_REPOSITORY');

export const LIST_JOB_COMPANIES_REPOSITORY = Symbol(
  'LIST_JOB_COMPANIES_REPOSITORY',
);
