export const LIST_JOB_USE_CASE = Symbol('LIST_JOB_USE_CASE');
export const LIST_JOB_REPOSITORY = Symbol('LIST_JOB_REPOSITORY');
export const CREATE_JOB_USE_CASE = Symbol('CREATE_JOB_USE_CASE');
export const CREATE_JOB_REPOSITORY = Symbol('CREATE_JOB_REPOSITORY');
